spring:
  application:
    name: minicloud
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    static-locations: file:src/main/resources/static/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniclouddb?createDatabaseIfNotExist=true
    username: root
    password: este5ban9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      resolve-lazily: true

var:
  env: dev # dev, prod
  title: ${spring.application.name}
  filepath: ./files
  admin:
    email: estebangonza2005@gmail.com
  email-api:
    url: https://emailapi-9qbt.onrender.com
    username: estebandev
    password: ZS0F5XebG6Q6ct4nry

logging:
  level:
    org.springframework.web: WARN 
    org.hibernate: WARN
    # org.springframework.security: TRACE
